//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventOfCode2017.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventOfCode2017.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{{{{},{&lt;&gt;,&lt;!!u&apos;!!!&gt;,,}!&gt;&quot;!!!!!&gt;},&lt;&gt;}}},{{{{{{{&lt;!&gt;,&lt;&quot;}!i&quot;!&gt;},&lt;a!!,&lt;!&gt;},&lt;{oo&lt;{!!&quot;!&gt;!a&gt;},&lt;&quot;!!&apos;&apos;!&gt;},&lt;!!!&gt;!,ie!&gt;,!!!&gt;&gt;}},{{}},{{{&lt;!&gt;},&lt;{e!&gt;,&gt;,&lt;!!e{,o}o&quot;!&gt;!&gt;,&lt;&quot;&quot;{uu{!!&apos;a&gt;},&lt;}a!!!!&gt;},{{&lt;,,ua&quot;o!&gt;!&gt;,&lt;!!a,&gt;}},{{}}}},{{},{&lt;!a{}&lt;!&gt;,&lt;!&gt;,&lt;!!u&gt;},{{},&lt;i,ai&apos;}!&gt;},&lt;!!!!!}e&apos;&apos;!!!!{&gt;}},{{{&lt;!&gt;!!,i!&gt;},&lt;u!!!&gt;o&quot;,&lt;!!{a!!u&apos;e!&gt;},&lt;,!&gt;},&lt;&gt;},&lt;&gt;},{{&lt;!&gt;},&lt;!&gt;}}!!!&gt;a!!u!!&apos;!&gt;,&lt;aa!!,e&gt;},{&lt;!o!&gt;},&lt;}&apos;u!!ii!&gt;!!!&gt;!!!&gt;{&lt;}!!!&gt;!!&lt;i!!}!!!&gt;&gt;}}}},{{{{{&lt;i!&quot;!!!!!&gt;!}!!!&gt;!&gt;,&lt;a&quot;!&gt;},&lt;,!!!!i{&gt;},&lt;&lt;!!!&gt;&lt;!!!&gt;&apos;!!!&gt;},&lt;e!&gt;e,!&lt;{!&gt;,&lt;!a&gt;},{&lt;!a&apos;i!&gt;,&lt;!&apos;!!!&gt;!&gt;},&lt;&lt;i&quot;&gt;,&lt;{o!u [rest of string was truncated]&qu....
        /// </summary>
        public static string Day9_Input {
            get {
                return ResourceManager.GetString("Day9_Input", resourceCulture);
            }
        }
    }
}
